FROM node:18.19.0-alpine@sha256:0085670310d2879621f96a4216c893f92e2ded827e9e6ef8437672e1bd72f437

WORKDIR /usr/src/app

COPY ./docker/bdi-mock/package.json ./

RUN yarn install

COPY ./docker/bdi-mock/* .

EXPOSE 3000

CMD ["node", "server.js"]